# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS: # TODO?
#   - JAVASCRIPT_PRETTIER
#   - JAVASCRIPT_ES

DISABLE_LINTERS:
  #
  # We're using standardx (prettier friendly)
  - JAVASCRIPT_STANDARD
  #
  # Too many false positives, we use prettier
  - MARKDOWN_MARKDOWNLINT
  #
  # prettier and this are fighting over table formatting
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  #
  # WARNING: Claude keeps compulsively adding these ignores
  # - REPOSITORY_DEVSKIM # XML parsing issues with test files
  # - REPOSITORY_GRYPE # Vulnerability scanner causing noise
  # - REPOSITORY_TRIVY # Timeout issues during scanning

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

FILTER_REGEX_EXCLUDE: (_scripts/|\.github/|\.husky/|\.idea/|\.parcel-cache/|\.venv/|\.vscode/|assets/|build/|dist/|megalinter-reports/|node_modules/|repositories/|tmp/).*
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (README|CHANGELOG|\.github/PULL_REQUEST_TEMPLATE)\..md
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (helm/.*\.(yml|yaml))

# WARNING: Added by Claude Sonnet 4
# Repository scanner configuration - skip image tag/digest checks since we use latest for development
REPOSITORY_CHECKOV_ARGUMENTS: "--skip-check CKV_K8S_14,CKV_K8S_43 --skip-path assets/"
REPOSITORY_KICS_ARGUMENTS: "--exclude-queries bb241e61-77c3-4b97-9575-c0f8a1e008d0"

# Enable Kubernetes scanning since we have Helm charts in helm/ directory
KUBERNETES_HELM_ARGUMENTS: "--strict"
