apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Values.namespace | default "web-app" | quote }}
  labels:
    app: {{ .Chart.Name | quote }}
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/part-of: "npm-web-sampler"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name | quote }}
        app.kubernetes.io/name: {{ .Chart.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/component: "frontend"
        app.kubernetes.io/part-of: "npm-web-sampler"
    spec:
      # Service account settings
      automountServiceAccountToken: false
      # Pod-level security defaults
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        # Add seccomp profile
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: {{ .Chart.Name | quote }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
        ports:
        - containerPort: 8080
        # Add health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        # Container-level security hardening
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
