apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Chart.Name | quote }}
  namespace: {{ .Values.namespace | default "web-app" | quote }}
spec:
  selector:
    app: {{ .Chart.Name | quote }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
