FROM nikolaik/python-nodejs:python3.13-nodejs23 AS base

FROM base AS project
WORKDIR /usr/project
COPY . .
RUN ls -la
RUN bash _scripts/clean.ba.sh

FROM project AS dev
RUN npm run setup:Dockerfile:dev && npm ci

FROM dev AS tested
RUN npm test --ignore-scripts

FROM dev AS dist
RUN npm run dist
RUN ls -la dist

# FROM project AS release # 2.1GB
# node:23-slim # ???MBs
FROM node:23-slim AS release
WORKDIR /opt/app
COPY --from=dist /usr/project/dist ./dist
COPY --from=project /usr/project/package*.json .
RUN npm install --production http-server
# RUN npm ci # Only needed for node apps. This is a static app.

FROM gcr.io/distroless/nodejs22-debian12 AS webapp
WORKDIR /opt/app
COPY --from=release /opt/app .
CMD ["/opt/app/node_modules/.bin/http-server", "./dist", "--port", "8080"]
