FROM node:24-slim AS base
RUN apt-get update && apt-get install -y python3 python3-pip python3.11-venv

FROM base AS project
WORKDIR /usr/project
COPY . .
RUN ls -la
RUN bash _scripts/clean.ba.sh

FROM project AS dev
RUN npm run setup:Dockerfile:dev && npm ci

FROM dev AS tested
RUN npm test --ignore-scripts

FROM dev AS dist
RUN npm run dist
RUN ls -la dist

FROM node:24-slim AS release
WORKDIR /opt/app
COPY --from=dist /usr/project/dist ./dist
COPY --from=project /usr/project/package*.json .
RUN npm install --production http-server

FROM gcr.io/distroless/nodejs24-debian12 AS webapp
WORKDIR /opt/app
COPY --from=release /opt/app .
USER nonroot
EXPOSE 8080
CMD ["/opt/app/node_modules/.bin/http-server", "./dist", "--port", "8080"]