name: Continuous Integration
on: 
  push:
  schedule:
    - cron: '* 0 * * *'
jobs:
  Build:
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16, 18]
    runs-on: ${{ matrix.os }}
    name: node ${{ matrix.node }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: setup node@16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: ls
        run: ls -la
      - name: setup
        run: npm run setup:ci --if-present
      - name: npm install
        run: npm ci
      - name: npm audit
        run: npm audit
        continue-on-error: true
      - name: npm test
        run: npm test
      - name: junit.xml
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests @ node:${{ matrix.node }}
          path: junit.xml
          reporter: jest-junit
      - name: npm run dist
        run: npm run dist
      - name: dist.zip
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  Validate:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: setup node@16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: ls
        run: ls -la
      - name: setup
        run: |
          npm run setup:ci --if-present
          npm ci
      - name: npm run validate
        run: npm run validate
      - name: junit.xml
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Integration Tests
          path: junit.xml
          reporter: jest-junit