name: ".github actions"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - .github/wokflows/branch.github.yml
      - .github/wokflows/**
      - .github/actions/**

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  codeQL:
    permissions:
      actions: read
      contents: read
      security-events: write

    name: CodeQL analyze
    uses: percebus/github-actions-compliance/.github/workflows/codeql_analyze.yml@main
    with:
      language: actions
