name: ".github actions"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - .github/actions/**
      - .github/wokflows/**

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# FIXME over-permission
permissions:
  checks: write
  issues: write
  actions: read
  contents: write
  pull-requests: write
  security-events: write

jobs:
  codeQL:
    needs: verify
    permissions:
      actions: read
      contents: read
      security-events: write

    name: CodeQL analyze
    uses: percebus/github-actions-compliance/.github/workflows/codeql_analyze.yml@main
    with:
      language: actions
