name: docker build
on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      docker_file:
        type: string
        description: Dockerfile location
        required: false
        default: ./Dockerfile

jobs:
  docker_build:
    # if: github.ref == 'refs/heads/main' # TODO
    name: docker build --file ${{ input.docker_file }} --target
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        DOCKER_TARGET:
          # - base
          # - project
          # - dev
          - test

          # final release
          # - release
          - webapp

    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      # XXX run inside container
      - name: bower install
        run: |
          npm run npm:install:global:ci
          npm run bower:install
      - name: 'docker build: ${{ matrix.DOCKER_TARGET }}'
        run: |
          docker build . \
            --file ${{ input.docker_file }} \
            --target ${{ matrix.DOCKER_TARGET }} \
            --tag ${{ env.REPOSITORY_NAME }}.${{ matrix.DOCKER_TARGET }}:${{ env.DOCKER_TAG_VERSION }}

      - name: Scan ${{ env.REPOSITORY_NAME }}.${{ matrix.DOCKER_TARGET }}:${{ env.DOCKER_TAG_VERSION }}
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ env.REPOSITORY_NAME }}.${{ matrix.DOCKER_TARGET }}:${{ env.DOCKER_TAG_VERSION }}
          fail-build: false
          output-format: sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
