name: docker build
on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      ssh-private-key:
        description: 'SSH private key'
        required: true

      docker_file:
        type: string
        description: Dockerfile location
        required: false
        default: ./Dockerfile

      image_tag:
        type: string
        description: Docker image tag
        required: false
        default: latest

jobs:
  docker_build:
    # if: github.ref == 'refs/heads/main' # TODO
    name: docker build --file ${{ inputs.docker_file }} --target
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        docker_target:
          # - base
          # - project
          # - dev
          - test

          # final release
          # - release
          - webapp

    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ inputs.ssh-private-key }}

      # XXX run inside container
      - name: bower install
        run: |
          npm run npm:install:global:ci
          npm run bower:install
      - name: 'docker build: ${{ matrix.docker_target }}'
        run: |
          docker build . \
            --file ${{ inputs.docker_file }} \
            --target ${{ matrix.docker_target }} \
            --tag ${{ env.REPOSITORY_NAME }}.${{ matrix.docker_target }}:${{ inputs.image_tag }}

      - name: Scan ${{ env.REPOSITORY_NAME }}.${{ matrix.docker_target }}:${{ inputs.image_tag }}
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ env.REPOSITORY_NAME }}.${{ matrix.docker_target }}:${{ inputs.image_tag }}
          fail-build: false
          output-format: sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
