name: "[C]ontinuous [I]ntegration @ main"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
    paths:
      - .github/wokflows/main.yml
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  # Disable HUSKY in CI
  HUSKY: 0
  DOCKER_BUILDKIT: 1
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: ${{ github.event.repository.name }}
  TF_IN_AUTOMATION: true

permissions:
  checks: write
  issues: write
  actions: read
  contents: write
  pull-requests: write
  security-events: write

jobs:
  # TODO? merge into verify?
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          echo "STACK_ID=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "environment=ci-main" >> $GITHUB_OUTPUT
          else
            echo "environment=ci-branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      STACK_ID: ${{ steps.set_variables.outputs.STACK_ID }}

  #
  verify:
    name: Verify
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: percebus/github-actions-nvm/.github/actions/install_and_use@main
      - uses: percebus/github-actions-npm/.github/actions/install@main

      - uses: percebus/github-actions-compliance/.github/actions/codeql_init_and_analyze@main
        with:
          language: javascript

      - uses: percebus/github-actions-helm/.github/actions/setup@main
      - uses: percebus/github-actions-terraform/.github/actions/setup@main

      # prettier
      - name: npm run lint:misc
        run: npm run lint:misc

      # standard
      - name: npm run lint:js
        run: npm run lint:js

      # htmllint (via grunt)
      - name: npm run lint:html
        run: npm run lint:html

      # FIXME: dockerlint
      # - name: npm run lint:docker
      #   run: npm run lint:docker

      # helm lint
      - name: npm run lint:helm
        run: npm run lint:helm

      # terraform lint
      - name: npm run lint:terraform
        run: npm run lint:terraform

      #
      # test
      - name: npm test
        run: npm test --ignore-scripts

      - uses: percebus/github-actions-testing/.github/actions/junit@main
        if: |
          (
            always() &&
            !startsWith(github.ref, 'refs/heads/dependabot/')
          )
        with:
          tests_name: Unit Tests
          summary_title: Unit Tests Summary
          check_name: Unit Tests Deltas
          comment_title: Unit Tests Deltas

      - name: semantic-release
        id: semantic-release
        run: |
          npm run semantic-release

          # SEE .releaserc.mjs: Check if the successCmd generated the file
          if [ -f .released ]; then
            echo "released=true" >> $GITHUB_OUTPUT
            echo "version=$(cat .release_version)" >> $GITHUB_OUTPUT
          else
            echo "released=false" >> $GITHUB_OUTPUT
          fi
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # TODO?
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # TODO move to -actions-npm
      - name: npm run dist
        if: steps.semantic-release.outputs.released == 'false'
        run: npm run dist

      - name: dist.zip
        if: always()
        uses: percebus/github-actions-common/.github/actions/artifact-upload@main
        with:
          name: dist
          path: ./dist

  #
  verify__matrix:
    if: github.ref == 'refs/heads/main'
    needs: verify
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        node:
          - 24
          - 25
          - 26
        OS:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.OS }}
    name: "Verify: node@${{ matrix.node }} @ ${{ matrix.OS }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}
          ls_options: ""

      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
        with:
          node-version: ${{ matrix.node }}

      - uses: percebus/github-actions-npm/.github/actions/install@main
        with:
          ls_options: ""

      - name: npm test
        run: npm test --ignore-scripts

      - uses: percebus/github-actions-testing/.github/actions/test-reporter@main
        if: always()
        with:
          name: Unit Tests @ node:${{ matrix.node }}@${{ matrix.os }}
          reporter: jest-junit
          files_pattern: junit.xml

      - name: npm run dist
        run: npm run dist

  #
  codeQL:
    needs: verify
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - actions

    name: CodeQL analyze
    uses: percebus/github-actions-compliance/.github/workflows/codeql_analyze.yml@main
    secrets: # XXX? redundant?
      SSH_KEY_PRIVATE: ${{ secrets.SSH_KEY_PRIVATE }}
    with:
      language: ${{ matrix.language }}

  #
  testem:
    if: false # FIXME not working
    name: "test'em"
    needs: verify
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      script: testem:ci:dot

  #
  docker_build__matrix:
    name: docker build --target
    needs: verify
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        include:
          # - base
          # - project
          - target: dev
            scan-image: false

          # final release
          # - release
          - target: web-app
            # Since it has already been run in docker-compose
            # We only run it when we want to scan it
            # which is only on main
            scan-image: ${{ github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - uses: percebus/github-actions-nvm/.github/actions/install_and_use@main

      - name: bower install
        run: |
          npm run npm:install:global:ci
          npm run bower:install

      - uses: percebus/github-actions-docker/.github/actions/build@main
        id: docker_build
        with:
          target: ${{ matrix.target }}
          image_tag: ${{ github.event.repository.name }}.${{ matrix.target }}:latest
          scan-image: ${{ matrix.scan-image && 'true' || 'false' }}

      - name: docker run
        if: matrix.target == 'dev'
        run: docker run ${{ steps.docker_build.outputs.image_tag }}

  #
  docker_build_next__matrix:
    if: github.ref == 'refs/heads/main'
    name: docker build --file Dockerfile.next --target
    needs: verify
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        include:
          # - base
          # - project
          - target: dev
            scan-image: false

          # final release
          # - release
          - target: web-app
            scan-image: ${{ github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - uses: percebus/github-actions-nvm/.github/actions/install_and_use@main
      - name: bower install
        run: |
          npm run npm:install:global:ci
          npm run bower:install

      - uses: percebus/github-actions-docker/.github/actions/build@main
        id: docker_build
        with:
          dockerfile: Dockerfile.next
          target: ${{ matrix.target }}
          image_tag: ${{ github.event.repository.name }}.${{ matrix.target }}:next
          scan-image: ${{ matrix.scan-image && 'true' || 'false' }}

      - name: docker run
        if: matrix.target == 'dev'
        run: docker run ${{ steps.docker_build.outputs.image_tag }}

  #
  docker_compose:
    name: docker compose
    needs: docker_build__matrix
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # XXX? run inside container
      - name: bower install
        run: |
          npm run npm:install:global:ci
          npm run bower:install

      - name: docker compose build
        run: docker compose build --no-cache

  #
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: verify
    runs-on: ubuntu-latest
    environment:
      url: ${{ steps.deployment.outputs.page_url }}
      name: github-pages

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: "pages"
      cancel-in-progress: false

    permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
      pages: write
      contents: read
      id-token: write
    steps:
      - name: dist.zip
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: ls
        run: ls -la ./dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Configure GitHub.IO Pages
        uses: actions/configure-pages@v5
      - name: https://percebus.GitHub.IO/npm-web-sampler
        id: deployment
        uses: actions/deploy-pages@v4

  #
  integration-tests:
    if: github.ref == 'refs/heads/main'
    needs: deploy-pages
    name: Integration Tests
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: percebus/github-actions-nvm/.github/actions/install_and_use@main
      - uses: percebus/github-actions-npm/.github/actions/install@main

      - name: npm run jest:ci:rest:npm-web-sampler
        run: npm run jest:ci:rest:npm-web-sampler

      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          tests_name: Integration Tests Results
          summary_title: Integration Tests Summary
          check_name: Integration Tests Deltas
          comment_title: Integration Tests Deltas

  #
  e2e-tests:
    if: github.ref == 'refs/heads/main'
    needs: integration-tests
    name: E2E Tests
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: percebus/github-actions-nvm/.github/actions/install_and_use@main
      - uses: percebus/github-actions-npm/.github/actions/install@main

      - name: npm run jest:playwright
        run: |
          npm run playwright:install
          npm run jest:playwright --ignore-scripts

      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          tests_name: E2E Tests Results
          summary_title: E2E Tests Summary
          check_name: E2E Tests Deltas
          comment_title: E2E Tests Deltas

  #
  terraform_test:
    name: terraform
    needs: setup
    uses: ./.github/workflows/test.yml
    with:
      override: true
      tflint-version: latest
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}

  #
  terraform_integration_tests:
    name: terraform @ test
    needs:
      - setup
      - terraform_test
    uses: ./.github/workflows/integration_tests.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    # with:
    #   environment: test
    #   TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
    #   TF_CLI_ARGS_test: ${{ needs.setup.outputs.TF_CLI_ARGS_test }}

  #
  terraform_ci-main_apply:
    name: "terraform @ ci-main"
    needs:
      - setup
      - terraform_integration_tests
    uses: ./.github/workflows/plan_and_apply.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ needs.setup.outputs.environment }}
      features_directory: features
      TF_CLI_ARGS_plan: "-var stack_id=${{ needs.setup.outputs.stack_id }}"

  terraform_ci-main_destroy:
    name: "terraform @ ci-main"
    needs: terraform_ci-main_apply
    uses: ./.github/workflows/apply.yml
    if: always()
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: ${{ needs.setup.outputs.environment }}
      destroy: true

  #
  terraform_dev_plan_and_apply:
    name: terraform @ dev
    if: ${{ github.ref_name == 'main' }}
    needs:
      - setup
      - terraform_ci-main_apply
    permissions:
      contents: read
      actions: read
      pull-requests: write
    uses: percebus/github-actions-terraform/.github/workflows/plan_and_apply.yml@main
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: dev
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"

  # TODO add helm
